import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-manrope',
  display: 'swap',
});

export const metadata = {
  title: "Supreme Group",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.className}>
      <body
        className={`${manrope.variable} antialiased`}
      >
        <div className="w-full h-dvh">
          {children}
        </div>
      </body>
    </html>
  );
}
